# The overall format is standard TOML format, v0.5.0.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/PuppetzMedia/Twisted-Tweaks/issues"
# The modid of the mod
modId="twistedtweaks"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}"
 # A display name for the mod
displayName="Twisted Tweaks"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/PuppetzMedia/Twisted-Tweaks"
# A text field displayed in the mod UI
credits="Hixfd398 & Csiers17"
# A text field displayed in the mod UI
authors="artdude543, MindlessPuppetz, Funwayguy, Lemons, yooksi"
# The description text for the mod (multi line!)
description='''Twisted Tweaks making the game ever more twisted.'''
